# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Item.create(name: 'Soda', description: 'Bubbly, delicious!', price: 1)
Item.create(name: 'Lemonade', description: 'Refreshing', price: 2)
Item.create(name: 'Collard Greens', description: 'Good and Good for you!', price: 1)
Item.create(name: 'Burger', description: "1/4 Angus 'beef'", price: 2, category_id: 1)
Item.create(name: 'Fries', description: 'No trans fat', price: 4)
Item.create(name: 'Steak', description: 'Ribeye 16 oz', price: 5, category_id: 1)
Item.create(name: 'Onion Rings', description: 'Deep fried. Deep pleasure', price: 6)
Item.create(name: 'Tater Tots', description: 'Not just for kids', price: 7)
Category.create(name: 'Meals')
Category.create(name: 'Drinks')
Category.create(name: 'Sides')
User.create(email: "admin@example.com", password: "password", role: 3)
User.create(email: "david@example.com", password: "password")
    user = User.create(email: "ryan@example.com", password: "password")
    user2 = User.create(email: "justin@example.com", password: "password")
    item = Item.create(name: "Soda", description: "Teh bubbles", price:4)
    item2 = Item.create(name: "Cake", description: "Its good", price: 7)
    @order1 = Order.create(user_id: user.id, status: 0)
    @order2 = Order.create(user_id: user.id, status: 1)
    @order3 = Order.create(user_id: user2.id, status: 2)
    @order4 = Order.create(user_id: user2.id, status: 3)
    OrderItem.create(order_id: @order1.id, quantity: 3, price: 4, item_id: item.id)
    OrderItem.create(order_id: @order2.id, quantity: 15, price: 4, item_id: item.id)
    OrderItem.create(order_id: @order3.id, quantity: 4, price: 7, item_id: item2.id)
    OrderItem.create(order_id: @order4.id, quantity: 25, price: 7, item_id: item2.id)
