# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Item.create(name: 'Lasagna', description: "Just like your granny made it", price: 7.99, category_id: 1, image_url: "http://cdn.thedailybeast.com/content/dailybeast/cheats/2013/02/09/french-gov-vows-to-punish-horsemeat-pushers/jcr:content/image.crop.800.500.jpg/45347925.cached.jpg")
Item.create(name: 'Burger', description: "Beef city, population: you", price: 6.99, category_id: 1, image_url: "http://www.slurrpy.com/wp-content/uploads/2015/09/chicken-burger-800x500.jpg")
Item.create(name: 'Seared Salmon', description: "This was swimming an hour ago", price: 10.99, category_id: 1, image_url: "http://curves.co.nz/sites/default/files/styles/main_image/public/CUR16617_Curves%20News_posts_Salmon.jpg?itok=KIJwI3oo")
Item.create(name: 'Bone-in Rib Eye', description: "Vegetarianism's downfall", price: 12.99, category_id: 1, image_url: "http://rothmanns2.dtpcreative.com/wp-content/uploads/2014/05/steak-btn.jpg")
Item.create(name: 'Soda', description: 'Bubbly & definitely not pop', price: 1.59, category_id: 2, image_url: "http://www.wall321.com/thumbnails/detail/20120306/drink%20macro%20ice%20cubes%201920x1200%20wallpaper_www.wall321.com_47.jpg")
Item.create(name: 'Lemonade', description: 'Made from the lemons life gave you', price: 1.69, category_id: 2, image_url: "http://roodepoortrecord.co.za/wp-content/uploads/sites/20/2015/08/6800363-lemonade-wallpaper-Medium.jpg?2a5d20")
Item.create(name: 'Beer', description: 'Proof God wants us to be happy', price: 3.99, category_id: 2, image_url: "http://cdn.thedailybeast.com/content/dailybeast/articles/2014/04/05/wine-snobs-there-s-a-beer-for-you/jcr:content/image.crop.800.500.jpg/46659654.cached.jpg")
Item.create(name: 'Milk', description: 'Grow big and strong', price: 1.99, category_id: 2, image_url: "http://nohealthnolife.net/wp-content/uploads/2015/07/1111.jpg")
Item.create(name: 'Fries', description: 'Now with no trans fat!', price: 1.99, category_id: 3, image_url: "http://www.foodadvisor.my/attachments/store/fill/800/500/8ab6f5150b3b9b4d70be356908e574932938da53fd55a45a379b593fc649/featured_image.jpg")
Item.create(name: 'Green Beans', description: 'Good and good for you!', price: 2.99, category_id: 3, image_url: "http://postcards.thepurplepassport.com/wp-content/uploads/2013/07/Green-Beans-with-Pork-at-Din-Tai-Fung_7026358825_l-e1372871437478.jpg")
Item.create(name: 'Onion Rings', description: 'Deep fried, deep pleasure', price: 2.99, category_id: 3, image_url: "https://lh3.googleusercontent.com/-xT2o5NUey3E/VY1JxkEtufI/AAAAAAAABkE/_hAiOPqRL0A/w800-h800/Spicy_Indian_Style_Onion_Rings_Recipe_thumbnail_1280x800.jpg")
Item.create(name: 'Mozzarella Sticks', description: 'Golden cheese logs from heaven', price: 2.59, category_id: 3, image_url: "http://dishinwithrebelle.com/wp-content/uploads/2013/06/PankoMozzarellaSticks-Ninja.jpg")
Category.create(name: 'Meals', image_url: "http://i0.wp.com/www.eatgeekplay.com/wp-content/uploads/2015/04/5280-website.jpg")
Category.create(name: 'Drinks', image_url: "http://www.restaurantdidar.com/bundles/statickarmadidar/img/drinks.jpg")
Category.create(name: 'Sides', image_url: "http://cosmoscookeville.com/wp-content/uploads/2013/09/cheesestix-700x300.jpg")
User.create(email: "admin@example.com", password: "password", role: 3)
User.create(email: "david@example.com", password: "password")
    user = User.create(email: "ryan@example.com", password: "password")
    user2 = User.create(email: "justin@example.com", password: "password")
    item = Item.create(name: "Soda", description: "Teh bubbles", price:4)
    item2 = Item.create(name: "Cake", description: "Its good", price: 7)
    @order1 = Order.create(user_id: user.id, status: 0)
    @order2 = Order.create(user_id: user.id, status: 1)
    @order3 = Order.create(user_id: user2.id, status: 2)
    @order4 = Order.create(user_id: user2.id, status: 3)
    OrderItem.create(order_id: @order1.id, quantity: 3, price: 4, item_id: item.id)
    OrderItem.create(order_id: @order2.id, quantity: 15, price: 4, item_id: item.id)
    OrderItem.create(order_id: @order3.id, quantity: 4, price: 7, item_id: item2.id)
    OrderItem.create(order_id: @order4.id, quantity: 25, price: 7, item_id: item2.id)
